/**
 * EngramBench Session-Level — does intercepting the investigation LOOP reduce
 * the TOTAL tokens of a session? (ADR-0002)
 *
 * `real-world.ts` measures per-file reduction. This measures the thing engram's
 * thesis rests on: a realistic investigation is `Grep(symbol) → Read(the files
 * that use it)`, and engram intercepts BOTH halves. We replay machine-generated
 * investigation traces through engram's REAL shipped handlers and count total
 * tool-call tokens over the SAME fixed sequence, in two arms.
 *
 * THE HONESTY MODEL (this is the whole point — read it):
 *   engram's packet is a SUBSET of the raw tool output. The grep packet is a
 *   ranked file list (not the match lines); the read packet is a structural
 *   summary (not the file's literal text). So when the agent's actual
 *   information need is NOT in the packet, it re-runs the raw call ON TOP of the
 *   packet — a "recall-recovery" cost. A bench that assumes the packet always
 *   substitutes is an OPTIMISTIC UPPER BOUND, not a lower bound.
 *
 *   So we don't report one number. We report the session reduction as a
 *   function of P = the fraction of intercepted calls where the agent still
 *   needs the raw content:
 *       engram_cost(step, P) = intercepted ? packet + P*baseline : baseline
 *   - P=0  : packet always suffices (optimistic ceiling)
 *   - P=1  : agent always needs raw too → engram is pure overhead (negative)
 *   - break-even P : the fallback rate below which engram still nets positive.
 *   The break-even P is the honest headline: "engram saves tokens on this
 *   investigation pattern as long as the agent falls back to raw content on
 *   fewer than <break-even>% of intercepted calls."
 *
 *   This is a STRUCTURAL context-token reduction, NOT a bill saving (prompt
 *   caching owns cost; engram's net over caching ≈ 0 per W1.9).
 *
 * Traces are generated by a RULE, never hand-picked: rank symbols by how many
 * files reference them, take the top K, emit `Grep(symbol) → Read(top-N caller
 * files)`. Symbol-grep baseline uses word-boundary `rg -w` (apples-to-apples
 * with engram's symbol answer). A grep-only stopword control proves no harm.
 *
 * Usage:
 *   npx tsx bench/session-level.ts [--project PATH] [--symbols K] [--reads N] [--out DIR]
 */
import {
  readFileSync,
  existsSync,
  mkdirSync,
  writeFileSync,
  rmSync,
  readdirSync,
} from "node:fs";
import { join, dirname, isAbsolute, basename } from "node:path";
import { fileURLToPath } from "node:url";
import { execFileSync } from "node:child_process";

const __dirname = dirname(fileURLToPath(import.meta.url));

function argOf(name: string, def: string): string {
  const idx = process.argv.indexOf(`--${name}`);
  if (idx === -1 || idx === process.argv.length - 1) return def;
  return process.argv[idx + 1];
}

const PROJECT = argOf("project", join(__dirname, ".."));
const TOP_SYMBOLS = parseInt(argOf("symbols", "12"), 10);
const READS_PER_TRACE = parseInt(argOf("reads", "3"), 10);
// Fraction of a trace's reads that are re-reads of an earlier file — models the
// "agent comes back to a file" pattern that dedup catches. Phase-0 measured
// 38–46% of real reads are same-session repeats (2,983 reads, 16 hook-logs);
// 0.4 is the reference. The dedup saving is reported as a function of this.
const REPEAT_RATE = parseFloat(argOf("repeat-rate", "0.4"));
const OUT_DIR = argOf("out", join(__dirname, "results"));
/** A filesystem-safe, deterministic session id per trace (for read dedup). */
const benchSession = (i: number): string => `bench-sess-${i}`;

/** Same heuristic as real-world.ts — keeps the two benches comparable. */
function estimateTokens(text: string): number {
  return Math.ceil(text.length / 4);
}

const CALLABLE = new Set([
  "function",
  "class",
  "method",
  "interface",
  "type",
  "variable",
]);

/** Strip `(params)` / `<generics>` so a miner label matches the bare symbol. */
function bareName(label: string): string {
  return label.split(/[(<]/)[0].trim();
}

// ── Tool-cost primitives ───────────────────────────────────────────

/**
 * Raw ripgrep output — the dump an agent's content grep puts in context.
 * `wholeWord` uses `-w` for symbol traces — the apples-to-apples baseline for
 * "find this symbol", vs noisy substring matching ("init" ⊃ "initialize").
 */
function rgRaw(pattern: string, root: string, wholeWord: boolean): string {
  // The `.` path arg is REQUIRED: under execFileSync rg has no TTY stdin, so
  // without a path it would read (empty) stdin and find nothing. rg then
  // prefixes every line with `./`; we strip it so the baseline isn't inflated
  // and the paths match the packet's relative `src/...` form (recall-coverage).
  const args = ["-n", "--no-heading", "--color=never"];
  if (wholeWord) args.push("-w");
  args.push("-e", pattern, ".");
  const strip = (out: string): string => out.replace(/^\.\//gm, "");
  try {
    return strip(
      execFileSync("rg", args, {
        cwd: root,
        encoding: "utf-8",
        maxBuffer: 128 * 1024 * 1024,
      })
    );
  } catch (e: unknown) {
    // rg exits 1 when there are zero matches; its (empty) stdout is on the error.
    return strip(
      e && typeof e === "object" && "stdout" in e
        ? String((e as { stdout?: unknown }).stdout ?? "")
        : ""
    );
  }
}

/** The deny packet text (what the agent pays), or null for a passthrough. */
function denyReason(result: unknown): string | null {
  if (!result || typeof result !== "object") return null;
  const out = (result as Record<string, unknown>).hookSpecificOutput as
    | Record<string, unknown>
    | undefined;
  const reason = out?.permissionDecisionReason;
  return typeof reason === "string" ? reason : null;
}

/**
 * The set of `file:line` match locations in an rg dump or an engram packet —
 * used to measure recall-coverage (does the packet surface the lines the agent
 * grepped for?). Robust to the leading-space difference between the two formats.
 */
function fileLineSet(text: string): Set<string> {
  const set = new Set<string>();
  for (const raw of text.split("\n")) {
    const line = raw.trim();
    const i1 = line.indexOf(":");
    if (i1 <= 0) continue;
    const i2 = line.indexOf(":", i1 + 1);
    if (i2 <= i1) continue;
    if (/^\d+$/.test(line.slice(i1 + 1, i2))) {
      set.add(line.slice(0, i2).replace(/^\.\//, "")); // normalised "file:line"
    }
  }
  return set;
}

/** Remove the per-trace served-reads stores the bench writes for dedup, so a
 *  later run never dedups against this run's records (and `.engram` stays clean). */
function clearBenchServedReads(root: string): void {
  try {
    const dir = join(root, ".engram");
    for (const name of readdirSync(dir)) {
      if (name.startsWith("served-reads-bench-sess-") && name.endsWith(".json")) {
        rmSync(join(dir, name), { force: true });
      }
    }
  } catch {
    /* ignore — best-effort cleanup */
  }
}

// ── Trace types ────────────────────────────────────────────────────

interface TraceStep {
  tool: "Grep" | "Read";
  arg: string;
}
interface Trace {
  name: string;
  kind: "symbol" | "control";
  steps: TraceStep[];
  /** Per-trace session id so a re-read of an earlier file triggers dedup. */
  sessionId: string;
}
interface StepResult {
  tool: string;
  arg: string;
  baseline: number;
  intercepted: boolean;
  packet: number; // engram's packet cost if intercepted, else == baseline
}
interface TraceResult {
  name: string;
  kind: "symbol" | "control";
  steps: StepResult[];
  baseline: number;
  /** intercepted-step baseline + packet totals — for the P-model. */
  interceptedBaseline: number;
  interceptedPacket: number;
  passthroughBaseline: number;
  /** recall-coverage: `file:line` match locations the raw grep would show vs how
   *  many the engram packet actually surfaces (a bare file list ≈ 0). */
  rawGrepLocs: number;
  coveredGrepLocs: number;
  /** Re-read (dedup) bucket — a CLEAN saving, NOT P-discounted: the content the
   *  pointer refers to is already in the agent's context. Kept separate from the
   *  P-model so the two savings aren't conflated. */
  dedupBaseline: number;
  dedupEngram: number;
}

/** engram cost for a trace at recall-recovery fraction P (first-reads/greps). */
function engramAt(t: TraceResult, p: number): number {
  return t.passthroughBaseline + t.interceptedPacket + p * t.interceptedBaseline;
}

/** A trace's first-read/grep baseline — excludes the re-read (dedup) bucket, so
 *  the P-model isn't diluted by re-reads (which are a separate clean saving). */
function pTraceBase(t: TraceResult): number {
  return t.passthroughBaseline + t.interceptedBaseline;
}

// ── Trace generation (deterministic rule, no cherry-picking) ───────

function buildTraces(
  nodes: ReadonlyArray<{ id: string; label: string; kind: string; sourceFile: string }>,
  edges: ReadonlyArray<{ source: string; target: string; relation: string; sourceFile: string }>
): Trace[] {
  const callsEdges = edges.filter((e) => e.relation === "calls");
  const fileById = new Map(
    nodes.filter((n) => n.kind === "file").map((n) => [n.id, n.sourceFile])
  );
  const defNameById = new Map<string, string>();
  for (const n of nodes) {
    if (CALLABLE.has(n.kind)) defNameById.set(n.id, bareName(n.label));
  }

  const sym2callers = new Map<string, Set<string>>();
  for (const e of callsEdges) {
    const name = defNameById.get(e.target);
    if (!name) continue;
    const file = fileById.get(e.source) ?? e.sourceFile;
    if (!sym2callers.has(name)) sym2callers.set(name, new Set());
    sym2callers.get(name)!.add(file);
  }

  const ranked = [...sym2callers.entries()]
    .map(([name, set]) => ({ name, callers: [...set].sort() }))
    .filter((s) => s.name.length >= 3 && s.callers.length >= 1)
    .sort(
      (a, b) =>
        b.callers.length - a.callers.length || a.name.localeCompare(b.name)
    )
    .slice(0, TOP_SYMBOLS);

  const symbolTraces: Trace[] = ranked.map((s, i) => {
    const reads = s.callers.slice(0, READS_PER_TRACE);
    // Re-read the first ⌊REPEAT_RATE·reads⌋ files — the agent revisiting its
    // working set. These are the reads dedup catches.
    const reReads = reads.slice(0, Math.round(REPEAT_RATE * reads.length));
    return {
      name: `investigate:${s.name}`,
      kind: "symbol" as const,
      sessionId: benchSession(i),
      steps: [
        { tool: "Grep" as const, arg: s.name },
        ...reads.map((f): TraceStep => ({ tool: "Read", arg: f })),
        ...reReads.map((f): TraceStep => ({ tool: "Read", arg: f })),
      ],
    };
  });

  // Control: stopword text-searches, GREP-ONLY. engram passes these through,
  // so control reduction is a true 0% — proof of no harm / no headline padding.
  const controlTraces: Trace[] = ["return", "error", "import"].map((p, i) => ({
    name: `text-search:${p}`,
    kind: "control" as const,
    sessionId: benchSession(1000 + i),
    steps: [{ tool: "Grep" as const, arg: p }],
  }));

  return [...symbolTraces, ...controlTraces];
}

// ── Trace costing ──────────────────────────────────────────────────

async function costTrace(
  trace: Trace,
  root: string,
  handleRead: (p: unknown) => Promise<unknown>,
  handleGrep: (p: unknown) => Promise<unknown>
): Promise<TraceResult> {
  const steps: StepResult[] = [];
  let baseline = 0;
  let interceptedBaseline = 0;
  let interceptedPacket = 0;
  let passthroughBaseline = 0;
  let rawGrepLocs = 0;
  let coveredGrepLocs = 0;
  let dedupBaseline = 0;
  let dedupEngram = 0;
  const seenReads = new Set<string>();

  for (const step of trace.steps) {
    let base = 0;
    let packetTokens: number | null = null;
    let isReread = false;

    if (step.tool === "Grep") {
      const rawOut = rgRaw(step.arg, root, trace.kind === "symbol");
      base = estimateTokens(rawOut);
      const r = await handleGrep({
        tool_name: "Grep",
        cwd: root,
        // content mode models a content-mode investigation — the case where
        // engram's call-site packet beats the raw grep. (A default
        // files_with_matches grep is cheaper than any packet → passthrough.)
        tool_input: { pattern: step.arg, output_mode: "content" },
      });
      const reason = denyReason(r);
      packetTokens = reason === null ? null : estimateTokens(reason);
      // recall-coverage: of the locations the raw grep would show, how many does
      // the packet actually surface? A bare file list ≈ 0; call-site lines high.
      if (reason !== null && trace.kind === "symbol") {
        const rawSet = fileLineSet(rawOut);
        const pktSet = fileLineSet(reason);
        rawGrepLocs += rawSet.size;
        for (const loc of rawSet) if (pktSet.has(loc)) coveredGrepLocs++;
      }
    } else {
      const abs = isAbsolute(step.arg) ? step.arg : join(root, step.arg);
      isReread = seenReads.has(abs);
      if (!isReread) seenReads.add(abs);
      let content = "";
      try {
        content = readFileSync(abs, "utf-8");
      } catch {
        content = "";
      }
      base = estimateTokens(content);
      // session_id makes the first read RECORD and a later re-read DEDUP.
      const r = await handleRead({
        tool_name: "Read",
        cwd: root,
        session_id: trace.sessionId,
        tool_input: { file_path: abs },
      });
      const reason = denyReason(r);
      packetTokens = reason === null ? null : estimateTokens(reason);
    }

    const intercepted = packetTokens !== null;
    steps.push({
      tool: step.tool,
      arg: step.arg,
      baseline: base,
      intercepted,
      packet: intercepted ? packetTokens! : base,
    });
    baseline += base;
    if (isReread) {
      // Re-read → dedup bucket (clean saving, not P-discounted).
      dedupBaseline += base;
      dedupEngram += intercepted ? packetTokens! : base;
    } else if (intercepted) {
      interceptedBaseline += base;
      interceptedPacket += packetTokens!;
    } else {
      passthroughBaseline += base;
    }
  }

  return {
    name: trace.name,
    kind: trace.kind,
    steps,
    baseline,
    interceptedBaseline,
    interceptedPacket,
    passthroughBaseline,
    rawGrepLocs,
    coveredGrepLocs,
    dedupBaseline,
    dedupEngram,
  };
}

// ── Main ───────────────────────────────────────────────────────────

async function main(): Promise<void> {
  console.log("EngramBench Session-Level");
  console.log("────────────────────────────────────────────────────────");
  console.log(`Project:     ${PROJECT}`);
  console.log(`Top symbols: ${TOP_SYMBOLS} · reads/trace: ${READS_PER_TRACE}`);
  console.log();

  if (!existsSync(join(PROJECT, ".engram", "graph.db"))) {
    console.error(
      `[FATAL] no .engram/graph.db at ${join(PROJECT, ".engram")}. Run \`engram init\` first.`
    );
    process.exit(1);
  }

  const { getStore } = await import("../src/core.js");
  const { handleRead } = await import("../src/intercept/handlers/read.js");
  const { handleGrep } = await import("../src/intercept/handlers/grep.js");

  const store = await getStore(PROJECT);
  const nodes = store.getAllNodes();
  const edges = store.getAllEdges();
  store.close();

  const traces = buildTraces(nodes as never, edges as never);
  if (traces.filter((t) => t.kind === "symbol").length === 0) {
    console.error(
      "[FATAL] no symbols with caller references. Run `engram init` to build the reference graph."
    );
    process.exit(1);
  }

  // Bench dedup uses per-trace `bench-sess-*` ids; clear any left over from a
  // prior run so a first read never dedups against a stale record.
  clearBenchServedReads(PROJECT);
  const results: TraceResult[] = [];
  for (const t of traces) {
    results.push(await costTrace(t, PROJECT, handleRead as never, handleGrep as never));
  }
  clearBenchServedReads(PROJECT);

  const symbol = results.filter((r) => r.kind === "symbol");
  const control = results.filter((r) => r.kind === "control");

  // ── First-read / grep aggregates (the P-model — packets are LOSSY) ──
  const pBase = symbol.reduce(
    (a, r) => a + r.passthroughBaseline + r.interceptedBaseline,
    0
  );
  const intBase = symbol.reduce((a, r) => a + r.interceptedBaseline, 0);
  const intPacket = symbol.reduce((a, r) => a + r.interceptedPacket, 0);

  // ── Dedup aggregates (re-reads — a CLEAN saving, not P-discounted) ──
  const dedupBase = symbol.reduce((a, r) => a + r.dedupBaseline, 0);
  const dedupEng = symbol.reduce((a, r) => a + r.dedupEngram, 0);
  const dedupReduction = dedupBase > 0 ? ((dedupBase - dedupEng) / dedupBase) * 100 : 0;

  // ── Whole session = first-reads/greps (P) + dedup (clean) ──
  const sessionBase = pBase + dedupBase;

  // Recall-coverage: of the match locations a raw content grep would show the
  // agent, what fraction does engram's packet actually surface? A bare file-list
  // packet ≈ 0% (the agent must re-grep → high effective P); call-site lines push
  // it up (lower effective P → the real saving moves toward the ceiling).
  const rawLocs = symbol.reduce((a, r) => a + r.rawGrepLocs, 0);
  const coveredLocs = symbol.reduce((a, r) => a + r.coveredGrepLocs, 0);
  const recallCoverage = rawLocs > 0 ? (coveredLocs / rawLocs) * 100 : 0;

  // P-model reduction over first-reads/greps only.
  const reductionAt = (p: number): number => {
    const eng = symbol.reduce((a, r) => a + engramAt(r, p), 0);
    return pBase > 0 ? ((pBase - eng) / pBase) * 100 : 0;
  };
  // Whole-session reduction = P-model engram + dedup (clean), over the full base.
  const sessionReductionAt = (p: number): number => {
    const eng = symbol.reduce((a, r) => a + engramAt(r, p), 0) + dedupEng;
    return sessionBase > 0 ? ((sessionBase - eng) / sessionBase) * 100 : 0;
  };
  // engram nets positive (first-read/grep model) while reduction(P) > 0:
  //   pBase = passΣ + intPacket + P*intBase  →  P = (intBase - intPacket)/intBase
  const breakEvenP = intBase > 0 ? (intBase - intPacket) / intBase : 0;

  // Per-trace optimistic (P=0) reductions — for median + range (P-model base).
  const perTraceP0 = symbol.map((r) =>
    pTraceBase(r) > 0 ? ((pTraceBase(r) - engramAt(r, 0)) / pTraceBase(r)) * 100 : 0
  );
  const sortedP0 = [...perTraceP0].sort((a, b) => a - b);
  const median = sortedP0[Math.floor(sortedP0.length / 2)] ?? 0;

  // Invariant: at P=0 engram must never cost more than the first-read/grep base.
  const regressions = symbol.filter((r) => engramAt(r, 0) > pTraceBase(r));

  // ── Print ──
  console.log(
    `${"Trace".padEnd(40)} ${"Baseline".padStart(10)} ${"Packet(P=0)".padStart(12)} ${"Reduce".padStart(8)}`
  );
  console.log("─".repeat(74));
  for (const r of symbol) {
    const pb = pTraceBase(r);
    const red = pb > 0 ? ((pb - engramAt(r, 0)) / pb) * 100 : 0;
    console.log(
      `${r.name.slice(0, 40).padEnd(40)} ${String(pb).padStart(10)} ${String(Math.round(engramAt(r, 0))).padStart(12)} ${red.toFixed(1).padStart(7)}%`
    );
  }
  console.log("─".repeat(74));
  console.log();

  console.log(
    `Grep recall-coverage: engram's call-site packets surface ${recallCoverage.toFixed(1)}% ` +
      `of the\n  ${rawLocs} match locations a raw content grep would show ` +
      `(a bare file list ≈ 0%).\n  Higher coverage → the agent re-greps less → lower effective P.`
  );
  console.log();

  console.log("Session reduction vs recall-recovery fraction P");
  console.log("(P = fraction of intercepted calls where the agent still needs raw content)");
  console.log("─".repeat(60));
  for (const p of [0, 0.25, 0.5, 0.75, 1.0]) {
    const bar = p === 0 ? "  ← optimistic ceiling" : p === 1 ? "  ← engram as pure overhead" : "";
    console.log(`  P=${p.toFixed(2)}:  ${reductionAt(p).toFixed(1).padStart(7)}%${bar}`);
  }
  console.log("─".repeat(60));
  console.log(
    `  BREAK-EVEN P = ${(breakEvenP * 100).toFixed(1)}%  ← engram nets positive` +
      ` while the agent\n               falls back to raw content on FEWER than` +
      ` ${(breakEvenP * 100).toFixed(0)}% of intercepted calls.`
  );
  console.log();

  console.log(
    `Read dedup (re-reads at R=${REPEAT_RATE}): ${dedupReduction.toFixed(1)}% of the re-read budget ` +
      `(${dedupBase} → ${Math.round(dedupEng)} tok).\n  A CLEAN saving — the re-read content is ` +
      `already in the agent's context, so it is NOT discounted by P.`
  );
  console.log();
  console.log("WHOLE SESSION (first-reads/greps at the P-model + dedup re-reads):");
  console.log(
    `  P=0.00: ${sessionReductionAt(0).toFixed(1)}%  ·  P=0.50: ${sessionReductionAt(0.5).toFixed(1)}%  ` +
      `(of ${sessionBase} session tokens)`
  );
  console.log();

  if (control.length > 0) {
    const cBase = control.reduce((a, r) => a + r.baseline, 0);
    const cEng = control.reduce((a, r) => a + engramAt(r, 0), 0);
    const cRed = cBase > 0 ? ((cBase - cEng) / cBase) * 100 : 0;
    console.log(
      `Control (grep-only text searches engram passes through): ${cRed.toFixed(1)}% ` +
        `— must be 0% (proves no harm / no padding).`
    );
  }
  console.log(`Per-trace median (P=0): ${median.toFixed(1)}%  ·  range ` +
    `${Math.min(...perTraceP0).toFixed(1)}%–${Math.max(...perTraceP0).toFixed(1)}%`);
  console.log();
  console.log("HONEST READ: the P=0 number is an OPTIMISTIC ceiling — it assumes");
  console.log("engram's structural packet fully answers what the agent grepped/read.");
  console.log("It doesn't always (the packet is a subset of the raw output), so the");
  console.log("real saving sits between P=0 and the break-even P, by workload. This is");
  console.log("a STRUCTURAL context-token reduction, NOT a bill saving.");
  console.log();

  if (regressions.length > 0) {
    console.log(`⚠ ${regressions.length} trace(s) where engram(P=0) cost MORE than baseline:`);
    for (const r of regressions) {
      console.log(`    ${r.name}: baseline ${pTraceBase(r)} > engram ${Math.round(engramAt(r, 0))}`);
    }
    console.log();
  }

  // ── Write results (project BASENAME only — never the absolute path) ──
  if (!existsSync(OUT_DIR)) mkdirSync(OUT_DIR, { recursive: true });
  const date = new Date().toISOString().slice(0, 10);
  const proj = basename(PROJECT);

  writeFileSync(
    join(OUT_DIR, `session-level-${date}.json`),
    JSON.stringify(
      {
        version: "session-level.v4",
        date: new Date().toISOString(),
        project: proj,
        config: {
          topSymbols: TOP_SYMBOLS,
          readsPerTrace: READS_PER_TRACE,
          repeatRate: REPEAT_RATE,
        },
        firstReadGrep: {
          baselineTokens: pBase,
          reductionByP: Object.fromEntries(
            [0, 0.25, 0.5, 0.75, 1.0].map((p) => [p, Number(reductionAt(p).toFixed(2))])
          ),
          breakEvenP: Number(breakEvenP.toFixed(4)),
          medianTraceReductionP0: Number(median.toFixed(2)),
          rangeP0: [Number(Math.min(...perTraceP0).toFixed(2)), Number(Math.max(...perTraceP0).toFixed(2))],
          grepRecallCoveragePct: Number(recallCoverage.toFixed(2)),
          grepRawMatchLocations: rawLocs,
        },
        dedup: {
          reReadBaselineTokens: dedupBase,
          reReadEngramTokens: dedupEng,
          reductionPct: Number(dedupReduction.toFixed(2)),
        },
        wholeSession: {
          baselineTokens: sessionBase,
          reductionAtP0: Number(sessionReductionAt(0).toFixed(2)),
          reductionAtP05: Number(sessionReductionAt(0.5).toFixed(2)),
        },
        regressions: regressions.map((r) => r.name),
        traces: results,
      },
      null,
      2
    )
  );

  const md = [
    `# EngramBench Session-Level — ${date}`,
    "",
    `**Project:** \`${proj}\` · top ${TOP_SYMBOLS} symbols · ${READS_PER_TRACE} reads/trace`,
    "",
    `## First-read / grep reduction vs recall-recovery fraction (P)`,
    "",
    `P = fraction of intercepted calls where the agent still needs the raw content`,
    `(because engram's packet is a *subset* of the raw grep/read output).`,
    "",
    `| P (recall-recovery) | Session reduction |`,
    `|---|---|`,
    ...[0, 0.25, 0.5, 0.75, 1.0].map(
      (p) =>
        `| ${p.toFixed(2)}${p === 0 ? " (optimistic ceiling)" : p === 1 ? " (pure overhead)" : ""} | ${reductionAt(p).toFixed(1)}% |`
    ),
    "",
    `**Break-even P = ${(breakEvenP * 100).toFixed(1)}%** — engram nets a positive session reduction as long as the agent falls back to raw content on fewer than ${(breakEvenP * 100).toFixed(0)}% of intercepted calls.`,
    "",
    `Per-trace median (P=0): **${median.toFixed(1)}%** · range ${Math.min(...perTraceP0).toFixed(1)}%–${Math.max(...perTraceP0).toFixed(1)}%. Control (text-search passthrough): 0%.`,
    "",
    `**Grep recall-coverage: ${recallCoverage.toFixed(1)}%** of the ${rawLocs} match locations a raw content grep would show are surfaced in engram's call-site packets (a bare file-list packet ≈ 0%). Higher coverage means the agent re-greps less — i.e. a *lower effective P*, which moves the real saving toward the ceiling. This is the measured proxy for the find-usages recall gain.`,
    "",
    `## Read dedup (re-reads) + whole session`,
    "",
    `**Read dedup: ${dedupReduction.toFixed(1)}%** of the re-read budget (${dedupBase} → ${Math.round(dedupEng)} tok) at a ${REPEAT_RATE} re-read rate (Phase-0 measured 38–46% of real reads are same-session repeats). A **clean** saving — the re-read content is already in the agent's context, so it is NOT discounted by P.`,
    "",
    `**Whole session** (first-reads/greps at the P-model + dedup re-reads, ${sessionBase} tokens): P=0 **${sessionReductionAt(0).toFixed(1)}%** · P=0.5 **${sessionReductionAt(0.5).toFixed(1)}%**.`,
    "",
    `> The **P=0 number is an OPTIMISTIC ceiling**, not a lower bound: it assumes engram's structural packet fully answers what the agent grepped/read. The packet is a subset of the raw output, so the real saving lies between P=0 and break-even, by workload (high recall-sufficiency on structural/discovery work, low when exact call sites are needed — the same bimodal split as W1.9). Structural context-token reduction, **not** a bill saving. Traces generated by a rule (top-${TOP_SYMBOLS} most-referenced symbols × caller files), word-boundary grep baseline.`,
    "",
    `## Reproduce`,
    "",
    "```bash",
    `engram init`,
    `npx tsx bench/session-level.ts --symbols ${TOP_SYMBOLS} --reads ${READS_PER_TRACE}`,
    "```",
  ].join("\n");
  writeFileSync(join(OUT_DIR, `session-level-${date}.md`), md);

  console.log("Results written:");
  console.log(`  ${join(OUT_DIR, `session-level-${date}.json`)}`);
  console.log(`  ${join(OUT_DIR, `session-level-${date}.md`)}`);
  console.log();

  // Regression guard (NOT a marketing claim): engram should net positive at a
  // realistic 50% fallback rate, never cost more at P=0, and the control = 0%.
  const controlOk =
    control.length === 0 ||
    control.reduce((a, r) => a + (engramAt(r, 0) - r.baseline), 0) === 0;
  const pass = reductionAt(0.5) > 0 && regressions.length === 0 && controlOk;
  console.log(
    `Guard (positive at P=0.5 · no P=0 regressions · control=0%): ${pass ? "✅ PASS" : "❌ FAIL"}`
  );
  process.exit(pass ? 0 : 1);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
