/**
 * CCS exporter — writes KG nodes as a CCS-format .context/index.md.
 * Exports pattern, decision, mistake, and high-traffic concept nodes.
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import type { GraphNode, GraphEdge } from "../graph/schema.js";

export interface CcsExportResult {
  readonly filePath: string;
  readonly sectionsWritten: number;
  readonly nodesExported: number;
}

const CCS_FILE = join(".context", "index.md");

const HEADER =
  "# Project Context\n\n" +
  "> Auto-generated by engram. See https://github.com/Agentic-Insights/codebase-context-spec\n";

function bullet(label: string): string {
  return `- ${label}`;
}

function buildSection(heading: string, nodes: GraphNode[]): string {
  if (nodes.length === 0) return "";
  const bullets = nodes.map((n) => bullet(n.label));
  return [`## ${heading}`, "", ...bullets, ""].join("\n");
}

/** Code node kinds usable as a structural fallback when no semantic nodes exist. */
const CODE_KINDS = new Set(["function", "class", "method", "interface", "type"]);

/**
 * Top code entities by connection count (graph degree). Used as a structural
 * fallback so CCS isn't empty on a fresh repo — patterns/decisions/mistakes/
 * concepts are mined over time, but the call graph exists at install time, the
 * same signal gen-mdc/gen-aider/gen-windsurfrules export.
 */
function topCodeEntities(
  nodes: readonly GraphNode[],
  edges: readonly GraphEdge[]
): GraphNode[] {
  const degree = new Map<string, number>();
  for (const e of edges) {
    degree.set(e.source, (degree.get(e.source) ?? 0) + 1);
    degree.set(e.target, (degree.get(e.target) ?? 0) + 1);
  }
  return nodes
    .filter((n) => CODE_KINDS.has(n.kind))
    .sort(
      (a, b) =>
        (degree.get(b.id) ?? 0) - (degree.get(a.id) ?? 0) ||
        a.label.localeCompare(b.label)
    )
    .slice(0, 20);
}

export async function exportCcs(projectRoot: string): Promise<CcsExportResult> {
  const { getStore } = await import("../core.js");
  const store = await getStore(projectRoot);

  try {
    const allNodes = store.getAllNodes();

    // Architecture Patterns — pattern nodes with confidence >= 0.8, by queryCount
    const patternNodes = allNodes
      .filter(
        (n) =>
          n.kind === "pattern" &&
          n.confidenceScore >= 0.8 &&
          (n.metadata as Record<string, unknown>).type !== "hot_file"
      )
      .sort((a, b) => b.queryCount - a.queryCount);

    // Decisions — all decision nodes, newest first
    const decisionNodes = allNodes
      .filter((n) => n.kind === "decision")
      .sort((a, b) => b.lastVerified - a.lastVerified);

    // Known Issues — mistake nodes by queryCount (most-hit first)
    const mistakeNodes = allNodes
      .filter((n) => n.kind === "mistake")
      .sort((a, b) => b.queryCount - a.queryCount);

    // Key Concepts — concept nodes with queryCount > 0, top 10
    const conceptNodes = allNodes
      .filter((n) => n.kind === "concept" && n.queryCount > 0)
      .sort((a, b) => b.queryCount - a.queryCount)
      .slice(0, 10);

    const semanticSections = [
      buildSection("Architecture Patterns", patternNodes),
      buildSection("Decisions", decisionNodes),
      buildSection("Known Issues", mistakeNodes),
      buildSection("Key Concepts", conceptNodes),
    ].filter((s) => s.length > 0);

    // Fresh repo: no semantic nodes mined yet → fall back to the call graph so
    // the file is useful at install time rather than an empty header.
    const fallbackEntities =
      semanticSections.length === 0
        ? topCodeEntities(allNodes, store.getAllEdges())
        : [];
    const sections =
      semanticSections.length > 0
        ? semanticSections
        : [buildSection("Key Code Entities", fallbackEntities)].filter(
            (s) => s.length > 0
          );

    const content = [HEADER, ...sections].join("\n");

    const outPath = join(projectRoot, CCS_FILE);
    mkdirSync(dirname(outPath), { recursive: true });
    writeFileSync(outPath, content, "utf-8");

    const nodesExported =
      patternNodes.length +
      decisionNodes.length +
      mistakeNodes.length +
      conceptNodes.length +
      fallbackEntities.length;

    return {
      filePath: outPath,
      sectionsWritten: sections.length,
      nodesExported,
    };
  } finally {
    store.close();
  }
}
